quarkus.lambda.handler=temperatureReportLambda
DDB_TABLE=TemperatureReport

quarkus.dynamodb.endpoint-override=http://localhost:4566
quarkus.dynamodb.aws.region=us-east-1
quarkus.dynamodb.aws.credentials.type=static
quarkus.dynamodb.aws.credentials.static-provider.access-key-id=AKIAR2GIPJXE2ENUJU6C
quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=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



