quarkus.dynamodb.endpoint-override=http://localhost:8000

quarkus.dynamodb.aws.region=eu-central-1
quarkus.dynamodb.aws.credentials.type=static
#quarkus.dynamodb.aws.credentials.type=json
quarkus.dynamodb.aws.credentials.static-provider.access-key-id=AKIATABSYIYPI5234TD6
quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=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
